env:
  browser: true
  commonjs: true
  es6: true
extends:
  - 'plugin:react/recommended'
  - standard
  - "eslint:recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
plugins:
  - react
  - '@typescript-eslint'
rules: {}
settings:
  react:
      version: detect
